image: zachdeibert/typescript


stages:
  - build
  - deploy


build:
  stage: build
  script:
    ## Compile all TypeScript files do JavaScript
    ## using the rules from tsconfig.json
    - tsc
    - rm js/*.ts
    ## Move the important files into a release directory
    - mkdir -p public
    - mv js public
    - mv fonts public
    - mv music public
    - mv css public
    - mv index.html public
  artifacts:
    paths:
      - public


pages:
  stage: deploy
  script:
    - echo "Nothing to do"
  artifacts:
    paths:
      - public
  only:
    - development
